version: '3.1'

services:
  db-mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: engine
    ports:
      - 3307:3306
    volumes:
      - /Users/DORSEy/data/mysql:/var/lib/mysql